#!/bin/bash
# Yandex Market Manager - One-shot setup and run
# Usage: ./setup_and_run.sh
# Run from project root. Uses DB password: yandex_password (change in .env after if needed)

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
PROJECT_ROOT="$SCRIPT_DIR"

# Fixed defaults (change these if you like, or edit .env after first run)
DB_USER="yandex_user"
DB_PASSWORD="yandex_password"
DB_NAME="yandex_market"
SECRET_KEY="yandex-market-secret-key-change-in-production-$(date +%s)"
# For access from another machine (e.g. VPS), set to http://YOUR_IP:3000
FRONTEND_URL="http://localhost:3000"
PUBLIC_URL="http://localhost:3000"

echo "=== Yandex Market Manager - Setup ==="
echo "Project root: $PROJECT_ROOT"
echo ""

# --- 1. Detect OS and install system dependencies ---
if [ -f /etc/os-release ]; then
  . /etc/os-release
  if [ "$ID" = "ubuntu" ] || [ "$ID" = "debian" ]; then
    echo "[1/6] Installing system packages (PostgreSQL, Python 3.11, Node.js)..."
    sudo apt-get update -qq
    sudo apt-get install -y -qq curl git build-essential postgresql postgresql-contrib \
      software-properties-common 2>/dev/null || true
    # Python 3.11
    if ! command -v python3.11 &>/dev/null; then
      sudo add-apt-repository -y ppa:deadsnakes/ppa 2>/dev/null || true
      sudo apt-get update -qq
      sudo apt-get install -y -qq python3.11 python3.11-venv python3.11-dev 2>/dev/null || true
    fi
    # Pip for Python 3.11
    if ! python3.11 -m pip --version &>/dev/null 2>&1; then
      curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 2>/dev/null || true
    fi
    # Node.js 20 if not present
    if ! command -v node &>/dev/null || ! node -v | grep -q "v1[89]\|v2"; then
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - 2>/dev/null || true
      sudo apt-get install -y -qq nodejs 2>/dev/null || true
    fi
    sudo systemctl start postgresql 2>/dev/null || true
    sudo systemctl enable postgresql 2>/dev/null || true
    echo "    System packages ready."
  else
    echo "[1/6] Not Ubuntu/Debian. Please ensure PostgreSQL, Python 3.11, and Node.js are installed."
    echo "    Skipping system install. Continuing with venv and DB setup..."
  fi
else
  echo "[1/6] Cannot detect OS. Ensure PostgreSQL, Python 3.11, and Node.js are installed."
fi

# --- 2. Create PostgreSQL user and database ---
echo "[2/6] Setting up PostgreSQL database..."
if command -v psql &>/dev/null; then
  sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';" 2>/dev/null || true
  sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE DATABASE $DB_NAME OWNER $DB_USER;" 2>/dev/null || true
  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;" 2>/dev/null || true
  sudo -u postgres psql -c "ALTER DATABASE $DB_NAME SET timezone TO 'UTC';" 2>/dev/null || true
  echo "    Database '$DB_NAME' and user '$DB_USER' ready."
else
  echo "    psql not found. Install PostgreSQL and re-run, or use Docker."
  exit 1
fi

# --- 3. Python venv and pip install ---
echo "[3/6] Creating Python virtualenv and installing dependencies..."
PYTHON=python3.11
if ! command -v python3.11 &>/dev/null; then
  PYTHON=python3
fi
if [ ! -d "venv" ]; then
  $PYTHON -m venv venv
fi
source venv/bin/activate
pip install -q --upgrade pip
pip install -q -r requirements.txt 2>/dev/null || pip install -q -r backend/requirements.txt
echo "    Python dependencies installed."

# --- 4. Write .env (project root and backend/ so uvicorn finds it when run from backend/) ---
echo "[4/6] Writing .env..."
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@localhost:5432/${DB_NAME}"
ENV_CONTENT="# Auto-generated by setup_and_run.sh
POSTGRES_USER=$DB_USER
POSTGRES_PASSWORD=$DB_PASSWORD
POSTGRES_DB=$DB_NAME
DATABASE_URL=$DATABASE_URL
SECRET_KEY=$SECRET_KEY
FRONTEND_URL=$FRONTEND_URL
PUBLIC_URL=$PUBLIC_URL
"
echo "$ENV_CONTENT" > .env
cp .env backend/.env 2>/dev/null || true
echo "    .env created."

# --- 5. Run database migrations / init ---
echo "[5/6] Initializing database (migrations and default data)..."
export $(grep -v '^#' .env | xargs)
cd backend
python init_db.py
cd "$PROJECT_ROOT"
echo "    Database initialized."

# --- 6. Install frontend deps (no build yet, so dev server can run) ---
echo "[6/6] Installing frontend dependencies..."
cd frontend
npm install --silent 2>/dev/null || npm install
cd "$PROJECT_ROOT"
echo "    Frontend dependencies installed."
echo ""

# --- Start backend in background, wait until ready, then start frontend ---
echo "=== Starting application ==="
source venv/bin/activate
export $(grep -v '^#' .env | xargs)

# Ensure backend/.env exists so uvicorn (run from backend/) loads it
cp "$PROJECT_ROOT/.env" "$PROJECT_ROOT/backend/.env" 2>/dev/null || true

# Start backend in background
cd "$PROJECT_ROOT/backend"
nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > ../backend.log 2>&1 &
BACKEND_PID=$!
echo $BACKEND_PID > "$PROJECT_ROOT/.backend.pid"
echo "Backend starting (PID $BACKEND_PID)..."
cd "$PROJECT_ROOT"

# Wait for backend to be up (up to 45 seconds)
BACKEND_READY=
for i in $(seq 1 45); do
  if curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/api/health 2>/dev/null | grep -q 200; then
    BACKEND_READY=1
    echo "Backend is ready."
    break
  fi
  sleep 1
done

if [ -z "$BACKEND_READY" ]; then
  echo ""
  echo "ERROR: Backend did not start. Check backend.log:"
  tail -n 30 backend.log
  echo ""
  echo "Fix the error above, then start backend manually:"
  echo "  cd backend && source ../venv/bin/activate && export \$(grep -v '^#' ../.env | xargs) && uvicorn app.main:app --host 0.0.0.0 --port 8000"
  echo "Then in another terminal run: cd frontend && npm run dev"
  echo "(Note: npm run dev must be run from the frontend/ folder, not backend/.)"
  exit 1
fi

# Start frontend (development server) in foreground
echo ""
echo "Frontend: http://localhost:3000 (and http://$(hostname -I 2>/dev/null | awk '{print $1}'):3000 if remote)"
echo "Ctrl+C stops frontend only; backend keeps running. To stop backend: kill \$(cat .backend.pid)"
echo ""
cd frontend
exec npm run dev
